version: 2
jobs:
  build:
    working_directory: ~/tabimemo2
    docker:
      - image: circleci/ruby:2.6.4-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          DATABASE_HOST: 127.0.0.1
          DATABASE_USER: root
          RAILS_ENV: test
      - image: circleci/mysql:5.6
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --ft_min_word_len=1
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-test-job-cache-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - v1-test-job-cache-bundle-{{ .Branch }}-
      - run:
          name: Bundle Install
          command: bundle install --path=vendor/bundle
      - save_cache:
          key: v1-test-job-cache-bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:create && bin/rails db:schema:load --trace
      - run:
          name: Run rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - run:
          name: Run rubocop
          commant: bundle exec rubocop
